services:
  - type: web
    name: jiocoders-portfolio
    runtime: docker
    region: singapore # or ohio, oregon, frankfurt, etc.
    plan: free # or starter, standard, etc.
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8080
      - key: DB_URL
        sync: false # User must enter this manually in dashboard
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_DRIVER_CLASS_NAME
        value: org.h2.Driver
      - key: DB_PLATFORM
        value: rg.hibernate.dialect.H2Dialect