spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4.1
          temperature: 0.2
        client:
          enabled: false
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: codellama:latest
          temperature: 0.7
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL:jdbc:h2:file:./data/portfolio;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
    driver-class-name: ${DB_DRIVER_CLASS_NAME:org.h2.Driver}
  jpa:
    database-platform: ${DB_PLATFORM:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: validate
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
jio:
  api:
    prefix: /jiocoders/v1
  
logging:
  level:
    root: INFO
    com.jiocoders.portfolio: INFO
    org.springframework.web: WARN
    org.hibernate: ERROR
