spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4.1
          temperature: 0.2
        client:
          enabled: false
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: codellama:latest
          temperature: 0.7

  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    driverClassName: ${DB_DRIVER_CLASS_NAME:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
  jpa:
    database-platform: ${DB_PLATFORM:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: validate
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
logging:
  level:
    root: INFO
    com.jiocoders.portfolio: DEBUG
    org.springframework.security: DEBUG
